# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# flatMap Operation Test - generates test data for flatMap pipeline

streams:
  input_target:
    topic: test-input-flatMap
    keyType: avro:SimpleFlatmapKey
    valueType: avro:SimpleFlatmapValue

producers:
  flatMap_data_producer:
    to: input_target
    interval: 2s
    generator:
      globalCode: |
        global flatMapCounter
        flatMapCounter = 0
      code: |
        global flatMapCounter
        flatMapCounter += 1

        current = flatMapCounter

        key = None
        if current % 10 != 0:
          key = dict()
          key["count"] = current

        value = None
        if current % 10 != 1:
          value = dict()
          value["text"] = f"flatMap test data - {current}"
          value["count"] = current

      expression: (key,value)
      resultType: (avro:SimpleFlatmapKey,avro:SimpleFlatmapValue)
